// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXD0fLBDP1yFMXlbuflYdmYAq-Wu8kNBc',
    appId: '1:323678300748:android:b647aa1800f8407001a2e9',
    messagingSenderId: '323678300748',
    projectId: 'bayu-firebase-e791e',
    databaseURL: 'https://bayu-firebase-e791e-default-rtdb.firebaseio.com',
    storageBucket: 'bayu-firebase-e791e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuiHRBA1N4jL94qzD9m7ZN2FFYIaZ_RY',
    appId: '1:323678300748:ios:188344c5dffa897d01a2e9',
    messagingSenderId: '323678300748',
    projectId: 'bayu-firebase-e791e',
    databaseURL: 'https://bayu-firebase-e791e-default-rtdb.firebaseio.com',
    storageBucket: 'bayu-firebase-e791e.firebasestorage.app',
    androidClientId: '323678300748-avvprp71fuk5fukcsaecclb0i9pos4i0.apps.googleusercontent.com',
    iosClientId: '323678300748-4sjv6eccqiis7lcbk2opo9kqj12anch4.apps.googleusercontent.com',
    iosBundleId: 'com.kas.kasautocareuser.kasAutocareUser',
  );
}
